name: {{cookiecutter.project_name}}_CI_CD


on:
  - push
  - pull_request

env:
  DJANGO_SETTINGS_MODULE: config.settings.dev

jobs:
  test:
    runs-on: ${% raw %}{{ matrix.os }}{% endraw %}
    strategy:
      max-parallel: 4
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: ['3.9', '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${% raw %}${{ matrix.os }}{% endraw %}
        uses: actions/setup-python@v3
        with:
          python-version: ${% raw %}{{ matrix.os }}{% endraw %}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check migrations
        run: |
          python src/manage.py makemigrations
          python src/manage.py migrate
          python src/manage.py check
      - name: Run tests
        run: |
            python src/manage.py test && flake8

            

